name: main-cd

on:
  push:
    branches: [ main ]
# manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and push docker
        run: |
          docker build -t coderyashiro/crust-files:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push coderyashiro/crust-files:latest
      - name: Upgrade home web
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull coderyashiro/crust-files:latest
            cd /opt/compose
            docker tag coderyashiro/crust-files:latest compose_crust-files
            docker-compose up -d crust-files
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}